services:
  # nginx
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
  # php
  app:
    build:
        dockerfile: ./php/Dockerfile
    volumes:
       - ./app:/app
  # mysql
  db:
     image: mysql:latest
     volumes:
        - mysqldata:/var/lib/mysql
     ports:
        - "3307:3306"
     restart: unless-stopped
     environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_USER: user 
        MYSQL_PASSWORD: pass
        MYSQL_DATABASE: iot
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      environment:
        - PMA_ARBITRARY=1
      restart: always
      ports:
        - 8001:80
  # redis

volumes:
  mysqldata: